// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.5
// source: api/proto/wecom_gateway.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Schedule types
type CreateScheduleRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Organizer           string                 `protobuf:"bytes,1,opt,name=organizer,proto3" json:"organizer,omitempty"`
	Summary             string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartTime           int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime             int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Attendees           []string               `protobuf:"bytes,6,rep,name=attendees,proto3" json:"attendees,omitempty"`
	Location            string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	RemindBeforeMinutes int32                  `protobuf:"varint,8,opt,name=remind_before_minutes,json=remindBeforeMinutes,proto3" json:"remind_before_minutes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateScheduleRequest) Reset() {
	*x = CreateScheduleRequest{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleRequest) ProtoMessage() {}

func (x *CreateScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleRequest.ProtoReflect.Descriptor instead.
func (*CreateScheduleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *CreateScheduleRequest) GetOrganizer() string {
	if x != nil {
		return x.Organizer
	}
	return ""
}

func (x *CreateScheduleRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CreateScheduleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateScheduleRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CreateScheduleRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *CreateScheduleRequest) GetAttendees() []string {
	if x != nil {
		return x.Attendees
	}
	return nil
}

func (x *CreateScheduleRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateScheduleRequest) GetRemindBeforeMinutes() int32 {
	if x != nil {
		return x.RemindBeforeMinutes
	}
	return 0
}

type Schedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	Organizer     string                 `protobuf:"bytes,2,opt,name=organizer,proto3" json:"organizer,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	StartTime     int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Attendees     []string               `protobuf:"bytes,7,rep,name=attendees,proto3" json:"attendees,omitempty"`
	Location      string                 `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	CalId         string                 `protobuf:"bytes,9,opt,name=cal_id,json=calId,proto3" json:"cal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *Schedule) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *Schedule) GetOrganizer() string {
	if x != nil {
		return x.Organizer
	}
	return ""
}

func (x *Schedule) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Schedule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Schedule) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Schedule) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Schedule) GetAttendees() []string {
	if x != nil {
		return x.Attendees
	}
	return nil
}

func (x *Schedule) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Schedule) GetCalId() string {
	if x != nil {
		return x.CalId
	}
	return ""
}

type GetSchedulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userid        string                 `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchedulesRequest) Reset() {
	*x = GetSchedulesRequest{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchedulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchedulesRequest) ProtoMessage() {}

func (x *GetSchedulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchedulesRequest.ProtoReflect.Descriptor instead.
func (*GetSchedulesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *GetSchedulesRequest) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *GetSchedulesRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetSchedulesRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetSchedulesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ScheduleList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedules     []*Schedule            `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleList) Reset() {
	*x = ScheduleList{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleList) ProtoMessage() {}

func (x *ScheduleList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleList.ProtoReflect.Descriptor instead.
func (*ScheduleList) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ScheduleList) GetSchedules() []*Schedule {
	if x != nil {
		return x.Schedules
	}
	return nil
}

type UpdateScheduleRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId          string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	Summary             string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartTime           int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime             int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Attendees           []string               `protobuf:"bytes,6,rep,name=attendees,proto3" json:"attendees,omitempty"`
	Location            string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	RemindBeforeMinutes int32                  `protobuf:"varint,8,opt,name=remind_before_minutes,json=remindBeforeMinutes,proto3" json:"remind_before_minutes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateScheduleRequest) Reset() {
	*x = UpdateScheduleRequest{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScheduleRequest) ProtoMessage() {}

func (x *UpdateScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScheduleRequest.ProtoReflect.Descriptor instead.
func (*UpdateScheduleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateScheduleRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *UpdateScheduleRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *UpdateScheduleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateScheduleRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *UpdateScheduleRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *UpdateScheduleRequest) GetAttendees() []string {
	if x != nil {
		return x.Attendees
	}
	return nil
}

func (x *UpdateScheduleRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateScheduleRequest) GetRemindBeforeMinutes() int32 {
	if x != nil {
		return x.RemindBeforeMinutes
	}
	return 0
}

type DeleteScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduleRequest) Reset() {
	*x = DeleteScheduleRequest{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduleRequest) ProtoMessage() {}

func (x *DeleteScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduleRequest.ProtoReflect.Descriptor instead.
func (*DeleteScheduleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteScheduleRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Meeting room types
type MeetingRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MbookingId    string                 `protobuf:"bytes,1,opt,name=mbooking_id,json=mbookingId,proto3" json:"mbooking_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Capacity      int32                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Building      string                 `protobuf:"bytes,5,opt,name=building,proto3" json:"building,omitempty"`
	Floor         string                 `protobuf:"bytes,6,opt,name=floor,proto3" json:"floor,omitempty"`
	Equipment     []string               `protobuf:"bytes,7,rep,name=equipment,proto3" json:"equipment,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeetingRoom) Reset() {
	*x = MeetingRoom{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeetingRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetingRoom) ProtoMessage() {}

func (x *MeetingRoom) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeetingRoom.ProtoReflect.Descriptor instead.
func (*MeetingRoom) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *MeetingRoom) GetMbookingId() string {
	if x != nil {
		return x.MbookingId
	}
	return ""
}

func (x *MeetingRoom) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MeetingRoom) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *MeetingRoom) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *MeetingRoom) GetBuilding() string {
	if x != nil {
		return x.Building
	}
	return ""
}

func (x *MeetingRoom) GetFloor() string {
	if x != nil {
		return x.Floor
	}
	return ""
}

func (x *MeetingRoom) GetEquipment() []string {
	if x != nil {
		return x.Equipment
	}
	return nil
}

func (x *MeetingRoom) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListMeetingRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Building      string                 `protobuf:"bytes,2,opt,name=building,proto3" json:"building,omitempty"`
	Floor         string                 `protobuf:"bytes,3,opt,name=floor,proto3" json:"floor,omitempty"`
	Capacity      int32                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Equipment     []string               `protobuf:"bytes,5,rep,name=equipment,proto3" json:"equipment,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,7,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMeetingRoomsRequest) Reset() {
	*x = ListMeetingRoomsRequest{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMeetingRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMeetingRoomsRequest) ProtoMessage() {}

func (x *ListMeetingRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMeetingRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListMeetingRoomsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *ListMeetingRoomsRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ListMeetingRoomsRequest) GetBuilding() string {
	if x != nil {
		return x.Building
	}
	return ""
}

func (x *ListMeetingRoomsRequest) GetFloor() string {
	if x != nil {
		return x.Floor
	}
	return ""
}

func (x *ListMeetingRoomsRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *ListMeetingRoomsRequest) GetEquipment() []string {
	if x != nil {
		return x.Equipment
	}
	return nil
}

func (x *ListMeetingRoomsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMeetingRoomsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type MeetingRoomList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*MeetingRoom         `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeetingRoomList) Reset() {
	*x = MeetingRoomList{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeetingRoomList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetingRoomList) ProtoMessage() {}

func (x *MeetingRoomList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeetingRoomList.ProtoReflect.Descriptor instead.
func (*MeetingRoomList) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *MeetingRoomList) GetRooms() []*MeetingRoom {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *MeetingRoomList) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type AvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingroomId string                 `protobuf:"bytes,1,opt,name=meetingroom_id,json=meetingroomId,proto3" json:"meetingroom_id,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailabilityRequest) Reset() {
	*x = AvailabilityRequest{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityRequest) ProtoMessage() {}

func (x *AvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityRequest.ProtoReflect.Descriptor instead.
func (*AvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *AvailabilityRequest) GetMeetingroomId() string {
	if x != nil {
		return x.MeetingroomId
	}
	return ""
}

func (x *AvailabilityRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *AvailabilityRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type TimeSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     int64                  `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSlot) Reset() {
	*x = TimeSlot{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSlot) ProtoMessage() {}

func (x *TimeSlot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSlot.ProtoReflect.Descriptor instead.
func (*TimeSlot) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *TimeSlot) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TimeSlot) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type TimeSlotList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*TimeSlot            `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSlotList) Reset() {
	*x = TimeSlotList{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSlotList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSlotList) ProtoMessage() {}

func (x *TimeSlotList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSlotList.ProtoReflect.Descriptor instead.
func (*TimeSlotList) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *TimeSlotList) GetSlots() []*TimeSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

type BookMeetingRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingroomId string                 `protobuf:"bytes,1,opt,name=meetingroom_id,json=meetingroomId,proto3" json:"meetingroom_id,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Booker        string                 `protobuf:"bytes,5,opt,name=booker,proto3" json:"booker,omitempty"`
	Attendees     []string               `protobuf:"bytes,6,rep,name=attendees,proto3" json:"attendees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookMeetingRoomRequest) Reset() {
	*x = BookMeetingRoomRequest{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookMeetingRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookMeetingRoomRequest) ProtoMessage() {}

func (x *BookMeetingRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookMeetingRoomRequest.ProtoReflect.Descriptor instead.
func (*BookMeetingRoomRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *BookMeetingRoomRequest) GetMeetingroomId() string {
	if x != nil {
		return x.MeetingroomId
	}
	return ""
}

func (x *BookMeetingRoomRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *BookMeetingRoomRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *BookMeetingRoomRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *BookMeetingRoomRequest) GetBooker() string {
	if x != nil {
		return x.Booker
	}
	return ""
}

func (x *BookMeetingRoomRequest) GetAttendees() []string {
	if x != nil {
		return x.Attendees
	}
	return nil
}

type BookingResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	ScheduleId    string                 `protobuf:"bytes,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingResult) Reset() {
	*x = BookingResult{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingResult) ProtoMessage() {}

func (x *BookingResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingResult.ProtoReflect.Descriptor instead.
func (*BookingResult) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *BookingResult) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *BookingResult) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *BookingResult) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *BookingResult) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// Message types
type TextMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiverType  string                 `protobuf:"bytes,1,opt,name=receiver_type,json=receiverType,proto3" json:"receiver_type,omitempty"`
	ReceiverIds   []string               `protobuf:"bytes,2,rep,name=receiver_ids,json=receiverIds,proto3" json:"receiver_ids,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Safe          bool                   `protobuf:"varint,4,opt,name=safe,proto3" json:"safe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextMessageRequest) Reset() {
	*x = TextMessageRequest{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextMessageRequest) ProtoMessage() {}

func (x *TextMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextMessageRequest.ProtoReflect.Descriptor instead.
func (*TextMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{15}
}

func (x *TextMessageRequest) GetReceiverType() string {
	if x != nil {
		return x.ReceiverType
	}
	return ""
}

func (x *TextMessageRequest) GetReceiverIds() []string {
	if x != nil {
		return x.ReceiverIds
	}
	return nil
}

func (x *TextMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TextMessageRequest) GetSafe() bool {
	if x != nil {
		return x.Safe
	}
	return false
}

type MarkdownMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiverType  string                 `protobuf:"bytes,1,opt,name=receiver_type,json=receiverType,proto3" json:"receiver_type,omitempty"`
	ReceiverIds   []string               `protobuf:"bytes,2,rep,name=receiver_ids,json=receiverIds,proto3" json:"receiver_ids,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkdownMessageRequest) Reset() {
	*x = MarkdownMessageRequest{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkdownMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkdownMessageRequest) ProtoMessage() {}

func (x *MarkdownMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkdownMessageRequest.ProtoReflect.Descriptor instead.
func (*MarkdownMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{16}
}

func (x *MarkdownMessageRequest) GetReceiverType() string {
	if x != nil {
		return x.ReceiverType
	}
	return ""
}

func (x *MarkdownMessageRequest) GetReceiverIds() []string {
	if x != nil {
		return x.ReceiverIds
	}
	return nil
}

func (x *MarkdownMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ImageMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiverType  string                 `protobuf:"bytes,1,opt,name=receiver_type,json=receiverType,proto3" json:"receiver_type,omitempty"`
	ReceiverIds   []string               `protobuf:"bytes,2,rep,name=receiver_ids,json=receiverIds,proto3" json:"receiver_ids,omitempty"`
	MediaId       string                 `protobuf:"bytes,3,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageMessageRequest) Reset() {
	*x = ImageMessageRequest{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageMessageRequest) ProtoMessage() {}

func (x *ImageMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageMessageRequest.ProtoReflect.Descriptor instead.
func (*ImageMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{17}
}

func (x *ImageMessageRequest) GetReceiverType() string {
	if x != nil {
		return x.ReceiverType
	}
	return ""
}

func (x *ImageMessageRequest) GetReceiverIds() []string {
	if x != nil {
		return x.ReceiverIds
	}
	return nil
}

func (x *ImageMessageRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type FileMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiverType  string                 `protobuf:"bytes,1,opt,name=receiver_type,json=receiverType,proto3" json:"receiver_type,omitempty"`
	ReceiverIds   []string               `protobuf:"bytes,2,rep,name=receiver_ids,json=receiverIds,proto3" json:"receiver_ids,omitempty"`
	MediaId       string                 `protobuf:"bytes,3,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMessageRequest) Reset() {
	*x = FileMessageRequest{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMessageRequest) ProtoMessage() {}

func (x *FileMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMessageRequest.ProtoReflect.Descriptor instead.
func (*FileMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{18}
}

func (x *FileMessageRequest) GetReceiverType() string {
	if x != nil {
		return x.ReceiverType
	}
	return ""
}

func (x *FileMessageRequest) GetReceiverIds() []string {
	if x != nil {
		return x.ReceiverIds
	}
	return nil
}

func (x *FileMessageRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type CardMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiverType  string                 `protobuf:"bytes,1,opt,name=receiver_type,json=receiverType,proto3" json:"receiver_type,omitempty"`
	ReceiverIds   []string               `protobuf:"bytes,2,rep,name=receiver_ids,json=receiverIds,proto3" json:"receiver_ids,omitempty"`
	CardContent   map[string]string      `protobuf:"bytes,3,rep,name=card_content,json=cardContent,proto3" json:"card_content,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardMessageRequest) Reset() {
	*x = CardMessageRequest{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardMessageRequest) ProtoMessage() {}

func (x *CardMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardMessageRequest.ProtoReflect.Descriptor instead.
func (*CardMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{19}
}

func (x *CardMessageRequest) GetReceiverType() string {
	if x != nil {
		return x.ReceiverType
	}
	return ""
}

func (x *CardMessageRequest) GetReceiverIds() []string {
	if x != nil {
		return x.ReceiverIds
	}
	return nil
}

func (x *CardMessageRequest) GetCardContent() map[string]string {
	if x != nil {
		return x.CardContent
	}
	return nil
}

type SendResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InvalidUserIds  []string               `protobuf:"bytes,1,rep,name=invalid_user_ids,json=invalidUserIds,proto3" json:"invalid_user_ids,omitempty"`
	InvalidPartyIds []string               `protobuf:"bytes,2,rep,name=invalid_party_ids,json=invalidPartyIds,proto3" json:"invalid_party_ids,omitempty"`
	InvalidTagIds   []string               `protobuf:"bytes,3,rep,name=invalid_tag_ids,json=invalidTagIds,proto3" json:"invalid_tag_ids,omitempty"`
	UnquotedUserIds []string               `protobuf:"bytes,4,rep,name=unquoted_user_ids,json=unquotedUserIds,proto3" json:"unquoted_user_ids,omitempty"`
	FailedUserIds   []string               `protobuf:"bytes,5,rep,name=failed_user_ids,json=failedUserIds,proto3" json:"failed_user_ids,omitempty"`
	FailedPartyIds  []string               `protobuf:"bytes,6,rep,name=failed_party_ids,json=failedPartyIds,proto3" json:"failed_party_ids,omitempty"`
	FailedTagIds    []string               `protobuf:"bytes,7,rep,name=failed_tag_ids,json=failedTagIds,proto3" json:"failed_tag_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendResult) Reset() {
	*x = SendResult{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResult) ProtoMessage() {}

func (x *SendResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResult.ProtoReflect.Descriptor instead.
func (*SendResult) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{20}
}

func (x *SendResult) GetInvalidUserIds() []string {
	if x != nil {
		return x.InvalidUserIds
	}
	return nil
}

func (x *SendResult) GetInvalidPartyIds() []string {
	if x != nil {
		return x.InvalidPartyIds
	}
	return nil
}

func (x *SendResult) GetInvalidTagIds() []string {
	if x != nil {
		return x.InvalidTagIds
	}
	return nil
}

func (x *SendResult) GetUnquotedUserIds() []string {
	if x != nil {
		return x.UnquotedUserIds
	}
	return nil
}

func (x *SendResult) GetFailedUserIds() []string {
	if x != nil {
		return x.FailedUserIds
	}
	return nil
}

func (x *SendResult) GetFailedPartyIds() []string {
	if x != nil {
		return x.FailedPartyIds
	}
	return nil
}

func (x *SendResult) GetFailedTagIds() []string {
	if x != nil {
		return x.FailedTagIds
	}
	return nil
}

// Admin types
type CreateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	CorpName      string                 `protobuf:"bytes,3,opt,name=corp_name,json=corpName,proto3" json:"corp_name,omitempty"`
	AppName       string                 `protobuf:"bytes,4,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	ExpiresDays   int32                  `protobuf:"varint,5,opt,name=expires_days,json=expiresDays,proto3" json:"expires_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyRequest) Reset() {
	*x = CreateAPIKeyRequest{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyRequest) ProtoMessage() {}

func (x *CreateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{21}
}

func (x *CreateAPIKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAPIKeyRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *CreateAPIKeyRequest) GetCorpName() string {
	if x != nil {
		return x.CorpName
	}
	return ""
}

func (x *CreateAPIKeyRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *CreateAPIKeyRequest) GetExpiresDays() int32 {
	if x != nil {
		return x.ExpiresDays
	}
	return 0
}

type APIKeyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Permissions   []string               `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	CorpName      string                 `protobuf:"bytes,4,opt,name=corp_name,json=corpName,proto3" json:"corp_name,omitempty"`
	AppName       string                 `protobuf:"bytes,5,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Disabled      bool                   `protobuf:"varint,7,opt,name=disabled,proto3" json:"disabled,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyInfo) Reset() {
	*x = APIKeyInfo{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyInfo) ProtoMessage() {}

func (x *APIKeyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyInfo.ProtoReflect.Descriptor instead.
func (*APIKeyInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{22}
}

func (x *APIKeyInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *APIKeyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIKeyInfo) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *APIKeyInfo) GetCorpName() string {
	if x != nil {
		return x.CorpName
	}
	return ""
}

func (x *APIKeyInfo) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *APIKeyInfo) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *APIKeyInfo) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *APIKeyInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *APIKeyInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ListAPIKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disabled      bool                   `protobuf:"varint,1,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAPIKeysRequest) Reset() {
	*x = ListAPIKeysRequest{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAPIKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAPIKeysRequest) ProtoMessage() {}

func (x *ListAPIKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAPIKeysRequest.ProtoReflect.Descriptor instead.
func (*ListAPIKeysRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{23}
}

func (x *ListAPIKeysRequest) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *ListAPIKeysRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAPIKeysRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type APIKeyList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*APIKeyInfo          `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyList) Reset() {
	*x = APIKeyList{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyList) ProtoMessage() {}

func (x *APIKeyList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyList.ProtoReflect.Descriptor instead.
func (*APIKeyList) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{24}
}

func (x *APIKeyList) GetKeys() []*APIKeyInfo {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *APIKeyList) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type DeleteAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAPIKeyRequest) Reset() {
	*x = DeleteAPIKeyRequest{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAPIKeyRequest) ProtoMessage() {}

func (x *DeleteAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteAPIKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type QueryAuditLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeyName    string                 `protobuf:"bytes,1,opt,name=api_key_name,json=apiKeyName,proto3" json:"api_key_name,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	StatusCode    int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StartTime     int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Limit         int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,8,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAuditLogsRequest) Reset() {
	*x = QueryAuditLogsRequest{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAuditLogsRequest) ProtoMessage() {}

func (x *QueryAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*QueryAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{26}
}

func (x *QueryAuditLogsRequest) GetApiKeyName() string {
	if x != nil {
		return x.ApiKeyName
	}
	return ""
}

func (x *QueryAuditLogsRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *QueryAuditLogsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *QueryAuditLogsRequest) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *QueryAuditLogsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *QueryAuditLogsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *QueryAuditLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryAuditLogsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type AuditLogList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*AuditLog            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogList) Reset() {
	*x = AuditLogList{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogList) ProtoMessage() {}

func (x *AuditLogList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogList.ProtoReflect.Descriptor instead.
func (*AuditLogList) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{27}
}

func (x *AuditLogList) GetLogs() []*AuditLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *AuditLogList) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type AuditLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ApiKeyId      string                 `protobuf:"bytes,4,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	ApiKeyName    string                 `protobuf:"bytes,5,opt,name=api_key_name,json=apiKeyName,proto3" json:"api_key_name,omitempty"`
	Method        string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	Query         string                 `protobuf:"bytes,8,opt,name=query,proto3" json:"query,omitempty"`
	Body          string                 `protobuf:"bytes,9,opt,name=body,proto3" json:"body,omitempty"`
	StatusCode    int32                  `protobuf:"varint,10,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	DurationMs    int32                  `protobuf:"varint,11,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ClientIp      string                 `protobuf:"bytes,12,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,13,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLog) Reset() {
	*x = AuditLog{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLog) ProtoMessage() {}

func (x *AuditLog) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLog.ProtoReflect.Descriptor instead.
func (*AuditLog) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{28}
}

func (x *AuditLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuditLog) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AuditLog) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *AuditLog) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

func (x *AuditLog) GetApiKeyName() string {
	if x != nil {
		return x.ApiKeyName
	}
	return ""
}

func (x *AuditLog) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AuditLog) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AuditLog) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AuditLog) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *AuditLog) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AuditLog) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *AuditLog) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *AuditLog) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type DashboardStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     int64                  `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardStatsRequest) Reset() {
	*x = DashboardStatsRequest{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardStatsRequest) ProtoMessage() {}

func (x *DashboardStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardStatsRequest.ProtoReflect.Descriptor instead.
func (*DashboardStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{29}
}

func (x *DashboardStatsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *DashboardStatsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type DashboardStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     int64                  `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	TotalApiKeys  int32                  `protobuf:"varint,3,opt,name=total_api_keys,json=totalApiKeys,proto3" json:"total_api_keys,omitempty"`
	ActiveApiKeys int32                  `protobuf:"varint,4,opt,name=active_api_keys,json=activeApiKeys,proto3" json:"active_api_keys,omitempty"`
	TotalCorps    int32                  `protobuf:"varint,5,opt,name=total_corps,json=totalCorps,proto3" json:"total_corps,omitempty"`
	TotalApps     int32                  `protobuf:"varint,6,opt,name=total_apps,json=totalApps,proto3" json:"total_apps,omitempty"`
	TotalRequests int32                  `protobuf:"varint,7,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	ErrorRequests int32                  `protobuf:"varint,8,opt,name=error_requests,json=errorRequests,proto3" json:"error_requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardStats) Reset() {
	*x = DashboardStats{}
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardStats) ProtoMessage() {}

func (x *DashboardStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wecom_gateway_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardStats.ProtoReflect.Descriptor instead.
func (*DashboardStats) Descriptor() ([]byte, []int) {
	return file_api_proto_wecom_gateway_proto_rawDescGZIP(), []int{30}
}

func (x *DashboardStats) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *DashboardStats) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *DashboardStats) GetTotalApiKeys() int32 {
	if x != nil {
		return x.TotalApiKeys
	}
	return 0
}

func (x *DashboardStats) GetActiveApiKeys() int32 {
	if x != nil {
		return x.ActiveApiKeys
	}
	return 0
}

func (x *DashboardStats) GetTotalCorps() int32 {
	if x != nil {
		return x.TotalCorps
	}
	return 0
}

func (x *DashboardStats) GetTotalApps() int32 {
	if x != nil {
		return x.TotalApps
	}
	return 0
}

func (x *DashboardStats) GetTotalRequests() int32 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *DashboardStats) GetErrorRequests() int32 {
	if x != nil {
		return x.ErrorRequests
	}
	return 0
}

var File_api_proto_wecom_gateway_proto protoreflect.FileDescriptor

const file_api_proto_wecom_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/wecom_gateway.proto\x12\rwecom.gateway\"\x99\x02\n" +
	"\x15CreateScheduleRequest\x12\x1c\n" +
	"\torganizer\x18\x01 \x01(\tR\torganizer\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x1c\n" +
	"\tattendees\x18\x06 \x03(\tR\tattendees\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x122\n" +
	"\x15remind_before_minutes\x18\b \x01(\x05R\x13remindBeforeMinutes\"\x90\x02\n" +
	"\bSchedule\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12\x1c\n" +
	"\torganizer\x18\x02 \x01(\tR\torganizer\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\x12\x1c\n" +
	"\tattendees\x18\a \x03(\tR\tattendees\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\x12\x15\n" +
	"\x06cal_id\x18\t \x01(\tR\x05calId\"}\n" +
	"\x13GetSchedulesRequest\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\tR\x06userid\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"E\n" +
	"\fScheduleList\x125\n" +
	"\tschedules\x18\x01 \x03(\v2\x17.wecom.gateway.ScheduleR\tschedules\"\x9c\x02\n" +
	"\x15UpdateScheduleRequest\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x1c\n" +
	"\tattendees\x18\x06 \x03(\tR\tattendees\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x122\n" +
	"\x15remind_before_minutes\x18\b \x01(\x05R\x13remindBeforeMinutes\"8\n" +
	"\x15DeleteScheduleRequest\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xe4\x01\n" +
	"\vMeetingRoom\x12\x1f\n" +
	"\vmbooking_id\x18\x01 \x01(\tR\n" +
	"mbookingId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x1a\n" +
	"\bbuilding\x18\x05 \x01(\tR\bbuilding\x12\x14\n" +
	"\x05floor\x18\x06 \x01(\tR\x05floor\x12\x1c\n" +
	"\tequipment\x18\a \x03(\tR\tequipment\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\"\xc7\x01\n" +
	"\x17ListMeetingRoomsRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x1a\n" +
	"\bbuilding\x18\x02 \x01(\tR\bbuilding\x12\x14\n" +
	"\x05floor\x18\x03 \x01(\tR\x05floor\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x05R\bcapacity\x12\x1c\n" +
	"\tequipment\x18\x05 \x03(\tR\tequipment\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\a \x01(\tR\x06cursor\"d\n" +
	"\x0fMeetingRoomList\x120\n" +
	"\x05rooms\x18\x01 \x03(\v2\x1a.wecom.gateway.MeetingRoomR\x05rooms\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"v\n" +
	"\x13AvailabilityRequest\x12%\n" +
	"\x0emeetingroom_id\x18\x01 \x01(\tR\rmeetingroomId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\"D\n" +
	"\bTimeSlot\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime\"=\n" +
	"\fTimeSlotList\x12-\n" +
	"\x05slots\x18\x01 \x03(\v2\x17.wecom.gateway.TimeSlotR\x05slots\"\xc9\x01\n" +
	"\x16BookMeetingRoomRequest\x12%\n" +
	"\x0emeetingroom_id\x18\x01 \x01(\tR\rmeetingroomId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\x12\x16\n" +
	"\x06booker\x18\x05 \x01(\tR\x06booker\x12\x1c\n" +
	"\tattendees\x18\x06 \x03(\tR\tattendees\"\x89\x01\n" +
	"\rBookingResult\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\tR\n" +
	"scheduleId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\"\x8a\x01\n" +
	"\x12TextMessageRequest\x12#\n" +
	"\rreceiver_type\x18\x01 \x01(\tR\freceiverType\x12!\n" +
	"\freceiver_ids\x18\x02 \x03(\tR\vreceiverIds\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04safe\x18\x04 \x01(\bR\x04safe\"z\n" +
	"\x16MarkdownMessageRequest\x12#\n" +
	"\rreceiver_type\x18\x01 \x01(\tR\freceiverType\x12!\n" +
	"\freceiver_ids\x18\x02 \x03(\tR\vreceiverIds\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"x\n" +
	"\x13ImageMessageRequest\x12#\n" +
	"\rreceiver_type\x18\x01 \x01(\tR\freceiverType\x12!\n" +
	"\freceiver_ids\x18\x02 \x03(\tR\vreceiverIds\x12\x19\n" +
	"\bmedia_id\x18\x03 \x01(\tR\amediaId\"w\n" +
	"\x12FileMessageRequest\x12#\n" +
	"\rreceiver_type\x18\x01 \x01(\tR\freceiverType\x12!\n" +
	"\freceiver_ids\x18\x02 \x03(\tR\vreceiverIds\x12\x19\n" +
	"\bmedia_id\x18\x03 \x01(\tR\amediaId\"\xf3\x01\n" +
	"\x12CardMessageRequest\x12#\n" +
	"\rreceiver_type\x18\x01 \x01(\tR\freceiverType\x12!\n" +
	"\freceiver_ids\x18\x02 \x03(\tR\vreceiverIds\x12U\n" +
	"\fcard_content\x18\x03 \x03(\v22.wecom.gateway.CardMessageRequest.CardContentEntryR\vcardContent\x1a>\n" +
	"\x10CardContentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x02\n" +
	"\n" +
	"SendResult\x12(\n" +
	"\x10invalid_user_ids\x18\x01 \x03(\tR\x0einvalidUserIds\x12*\n" +
	"\x11invalid_party_ids\x18\x02 \x03(\tR\x0finvalidPartyIds\x12&\n" +
	"\x0finvalid_tag_ids\x18\x03 \x03(\tR\rinvalidTagIds\x12*\n" +
	"\x11unquoted_user_ids\x18\x04 \x03(\tR\x0funquotedUserIds\x12&\n" +
	"\x0ffailed_user_ids\x18\x05 \x03(\tR\rfailedUserIds\x12(\n" +
	"\x10failed_party_ids\x18\x06 \x03(\tR\x0efailedPartyIds\x12$\n" +
	"\x0efailed_tag_ids\x18\a \x03(\tR\ffailedTagIds\"\xa6\x01\n" +
	"\x13CreateAPIKeyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\x12\x1b\n" +
	"\tcorp_name\x18\x03 \x01(\tR\bcorpName\x12\x19\n" +
	"\bapp_name\x18\x04 \x01(\tR\aappName\x12!\n" +
	"\fexpires_days\x18\x05 \x01(\x05R\vexpiresDays\"\x83\x02\n" +
	"\n" +
	"APIKeyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vpermissions\x18\x03 \x03(\tR\vpermissions\x12\x1b\n" +
	"\tcorp_name\x18\x04 \x01(\tR\bcorpName\x12\x19\n" +
	"\bapp_name\x18\x05 \x01(\tR\aappName\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\x12\x1a\n" +
	"\bdisabled\x18\a \x01(\bR\bdisabled\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"^\n" +
	"\x12ListAPIKeysRequest\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"\\\n" +
	"\n" +
	"APIKeyList\x12-\n" +
	"\x04keys\x18\x01 \x03(\v2\x19.wecom.gateway.APIKeyInfoR\x04keys\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"%\n" +
	"\x13DeleteAPIKeyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xee\x01\n" +
	"\x15QueryAuditLogsRequest\x12 \n" +
	"\fapi_key_name\x18\x01 \x01(\tR\n" +
	"apiKeyName\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\b \x01(\tR\x06cursor\"\\\n" +
	"\fAuditLogList\x12+\n" +
	"\x04logs\x18\x01 \x03(\v2\x17.wecom.gateway.AuditLogR\x04logs\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\xe6\x02\n" +
	"\bAuditLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x04 \x01(\tR\bapiKeyId\x12 \n" +
	"\fapi_key_name\x18\x05 \x01(\tR\n" +
	"apiKeyName\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\b \x01(\tR\x05query\x12\x12\n" +
	"\x04body\x18\t \x01(\tR\x04body\x12\x1f\n" +
	"\vstatus_code\x18\n" +
	" \x01(\x05R\n" +
	"statusCode\x12\x1f\n" +
	"\vduration_ms\x18\v \x01(\x05R\n" +
	"durationMs\x12\x1b\n" +
	"\tclient_ip\x18\f \x01(\tR\bclientIp\x12\x1b\n" +
	"\terror_msg\x18\r \x01(\tR\berrorMsg\"Q\n" +
	"\x15DashboardStatsRequest\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime\"\xa6\x02\n" +
	"\x0eDashboardStats\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime\x12$\n" +
	"\x0etotal_api_keys\x18\x03 \x01(\x05R\ftotalApiKeys\x12&\n" +
	"\x0factive_api_keys\x18\x04 \x01(\x05R\ractiveApiKeys\x12\x1f\n" +
	"\vtotal_corps\x18\x05 \x01(\x05R\n" +
	"totalCorps\x12\x1d\n" +
	"\n" +
	"total_apps\x18\x06 \x01(\x05R\ttotalApps\x12%\n" +
	"\x0etotal_requests\x18\a \x01(\x05R\rtotalRequests\x12%\n" +
	"\x0eerror_requests\x18\b \x01(\x05R\rerrorRequests2\xe0\a\n" +
	"\fWeComGateway\x12O\n" +
	"\x0eCreateSchedule\x12$.wecom.gateway.CreateScheduleRequest\x1a\x17.wecom.gateway.Schedule\x12O\n" +
	"\fGetSchedules\x12\".wecom.gateway.GetSchedulesRequest\x1a\x1b.wecom.gateway.ScheduleList\x12O\n" +
	"\x0eUpdateSchedule\x12$.wecom.gateway.UpdateScheduleRequest\x1a\x17.wecom.gateway.Schedule\x12U\n" +
	"\x0eDeleteSchedule\x12$.wecom.gateway.DeleteScheduleRequest\x1a\x1d.wecom.gateway.DeleteResponse\x12Z\n" +
	"\x10ListMeetingRooms\x12&.wecom.gateway.ListMeetingRoomsRequest\x1a\x1e.wecom.gateway.MeetingRoomList\x12V\n" +
	"\x13GetRoomAvailability\x12\".wecom.gateway.AvailabilityRequest\x1a\x1b.wecom.gateway.TimeSlotList\x12V\n" +
	"\x0fBookMeetingRoom\x12%.wecom.gateway.BookMeetingRoomRequest\x1a\x1c.wecom.gateway.BookingResult\x12H\n" +
	"\bSendText\x12!.wecom.gateway.TextMessageRequest\x1a\x19.wecom.gateway.SendResult\x12P\n" +
	"\fSendMarkdown\x12%.wecom.gateway.MarkdownMessageRequest\x1a\x19.wecom.gateway.SendResult\x12J\n" +
	"\tSendImage\x12\".wecom.gateway.ImageMessageRequest\x1a\x19.wecom.gateway.SendResult\x12H\n" +
	"\bSendFile\x12!.wecom.gateway.FileMessageRequest\x1a\x19.wecom.gateway.SendResult\x12H\n" +
	"\bSendCard\x12!.wecom.gateway.CardMessageRequest\x1a\x19.wecom.gateway.SendResult2\xb1\x03\n" +
	"\x11WeComGatewayAdmin\x12M\n" +
	"\fCreateAPIKey\x12\".wecom.gateway.CreateAPIKeyRequest\x1a\x19.wecom.gateway.APIKeyInfo\x12K\n" +
	"\vListAPIKeys\x12!.wecom.gateway.ListAPIKeysRequest\x1a\x19.wecom.gateway.APIKeyList\x12Q\n" +
	"\fDeleteAPIKey\x12\".wecom.gateway.DeleteAPIKeyRequest\x1a\x1d.wecom.gateway.DeleteResponse\x12S\n" +
	"\x0eQueryAuditLogs\x12$.wecom.gateway.QueryAuditLogsRequest\x1a\x1b.wecom.gateway.AuditLogList\x12X\n" +
	"\x11GetDashboardStats\x12$.wecom.gateway.DashboardStatsRequest\x1a\x1d.wecom.gateway.DashboardStatsB\x19Z\x17wecom-gateway/api/protob\x06proto3"

var (
	file_api_proto_wecom_gateway_proto_rawDescOnce sync.Once
	file_api_proto_wecom_gateway_proto_rawDescData []byte
)

func file_api_proto_wecom_gateway_proto_rawDescGZIP() []byte {
	file_api_proto_wecom_gateway_proto_rawDescOnce.Do(func() {
		file_api_proto_wecom_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_wecom_gateway_proto_rawDesc), len(file_api_proto_wecom_gateway_proto_rawDesc)))
	})
	return file_api_proto_wecom_gateway_proto_rawDescData
}

var file_api_proto_wecom_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_api_proto_wecom_gateway_proto_goTypes = []any{
	(*CreateScheduleRequest)(nil),   // 0: wecom.gateway.CreateScheduleRequest
	(*Schedule)(nil),                // 1: wecom.gateway.Schedule
	(*GetSchedulesRequest)(nil),     // 2: wecom.gateway.GetSchedulesRequest
	(*ScheduleList)(nil),            // 3: wecom.gateway.ScheduleList
	(*UpdateScheduleRequest)(nil),   // 4: wecom.gateway.UpdateScheduleRequest
	(*DeleteScheduleRequest)(nil),   // 5: wecom.gateway.DeleteScheduleRequest
	(*DeleteResponse)(nil),          // 6: wecom.gateway.DeleteResponse
	(*MeetingRoom)(nil),             // 7: wecom.gateway.MeetingRoom
	(*ListMeetingRoomsRequest)(nil), // 8: wecom.gateway.ListMeetingRoomsRequest
	(*MeetingRoomList)(nil),         // 9: wecom.gateway.MeetingRoomList
	(*AvailabilityRequest)(nil),     // 10: wecom.gateway.AvailabilityRequest
	(*TimeSlot)(nil),                // 11: wecom.gateway.TimeSlot
	(*TimeSlotList)(nil),            // 12: wecom.gateway.TimeSlotList
	(*BookMeetingRoomRequest)(nil),  // 13: wecom.gateway.BookMeetingRoomRequest
	(*BookingResult)(nil),           // 14: wecom.gateway.BookingResult
	(*TextMessageRequest)(nil),      // 15: wecom.gateway.TextMessageRequest
	(*MarkdownMessageRequest)(nil),  // 16: wecom.gateway.MarkdownMessageRequest
	(*ImageMessageRequest)(nil),     // 17: wecom.gateway.ImageMessageRequest
	(*FileMessageRequest)(nil),      // 18: wecom.gateway.FileMessageRequest
	(*CardMessageRequest)(nil),      // 19: wecom.gateway.CardMessageRequest
	(*SendResult)(nil),              // 20: wecom.gateway.SendResult
	(*CreateAPIKeyRequest)(nil),     // 21: wecom.gateway.CreateAPIKeyRequest
	(*APIKeyInfo)(nil),              // 22: wecom.gateway.APIKeyInfo
	(*ListAPIKeysRequest)(nil),      // 23: wecom.gateway.ListAPIKeysRequest
	(*APIKeyList)(nil),              // 24: wecom.gateway.APIKeyList
	(*DeleteAPIKeyRequest)(nil),     // 25: wecom.gateway.DeleteAPIKeyRequest
	(*QueryAuditLogsRequest)(nil),   // 26: wecom.gateway.QueryAuditLogsRequest
	(*AuditLogList)(nil),            // 27: wecom.gateway.AuditLogList
	(*AuditLog)(nil),                // 28: wecom.gateway.AuditLog
	(*DashboardStatsRequest)(nil),   // 29: wecom.gateway.DashboardStatsRequest
	(*DashboardStats)(nil),          // 30: wecom.gateway.DashboardStats
	nil,                             // 31: wecom.gateway.CardMessageRequest.CardContentEntry
}
var file_api_proto_wecom_gateway_proto_depIdxs = []int32{
	1,  // 0: wecom.gateway.ScheduleList.schedules:type_name -> wecom.gateway.Schedule
	7,  // 1: wecom.gateway.MeetingRoomList.rooms:type_name -> wecom.gateway.MeetingRoom
	11, // 2: wecom.gateway.TimeSlotList.slots:type_name -> wecom.gateway.TimeSlot
	31, // 3: wecom.gateway.CardMessageRequest.card_content:type_name -> wecom.gateway.CardMessageRequest.CardContentEntry
	22, // 4: wecom.gateway.APIKeyList.keys:type_name -> wecom.gateway.APIKeyInfo
	28, // 5: wecom.gateway.AuditLogList.logs:type_name -> wecom.gateway.AuditLog
	0,  // 6: wecom.gateway.WeComGateway.CreateSchedule:input_type -> wecom.gateway.CreateScheduleRequest
	2,  // 7: wecom.gateway.WeComGateway.GetSchedules:input_type -> wecom.gateway.GetSchedulesRequest
	4,  // 8: wecom.gateway.WeComGateway.UpdateSchedule:input_type -> wecom.gateway.UpdateScheduleRequest
	5,  // 9: wecom.gateway.WeComGateway.DeleteSchedule:input_type -> wecom.gateway.DeleteScheduleRequest
	8,  // 10: wecom.gateway.WeComGateway.ListMeetingRooms:input_type -> wecom.gateway.ListMeetingRoomsRequest
	10, // 11: wecom.gateway.WeComGateway.GetRoomAvailability:input_type -> wecom.gateway.AvailabilityRequest
	13, // 12: wecom.gateway.WeComGateway.BookMeetingRoom:input_type -> wecom.gateway.BookMeetingRoomRequest
	15, // 13: wecom.gateway.WeComGateway.SendText:input_type -> wecom.gateway.TextMessageRequest
	16, // 14: wecom.gateway.WeComGateway.SendMarkdown:input_type -> wecom.gateway.MarkdownMessageRequest
	17, // 15: wecom.gateway.WeComGateway.SendImage:input_type -> wecom.gateway.ImageMessageRequest
	18, // 16: wecom.gateway.WeComGateway.SendFile:input_type -> wecom.gateway.FileMessageRequest
	19, // 17: wecom.gateway.WeComGateway.SendCard:input_type -> wecom.gateway.CardMessageRequest
	21, // 18: wecom.gateway.WeComGatewayAdmin.CreateAPIKey:input_type -> wecom.gateway.CreateAPIKeyRequest
	23, // 19: wecom.gateway.WeComGatewayAdmin.ListAPIKeys:input_type -> wecom.gateway.ListAPIKeysRequest
	25, // 20: wecom.gateway.WeComGatewayAdmin.DeleteAPIKey:input_type -> wecom.gateway.DeleteAPIKeyRequest
	26, // 21: wecom.gateway.WeComGatewayAdmin.QueryAuditLogs:input_type -> wecom.gateway.QueryAuditLogsRequest
	29, // 22: wecom.gateway.WeComGatewayAdmin.GetDashboardStats:input_type -> wecom.gateway.DashboardStatsRequest
	1,  // 23: wecom.gateway.WeComGateway.CreateSchedule:output_type -> wecom.gateway.Schedule
	3,  // 24: wecom.gateway.WeComGateway.GetSchedules:output_type -> wecom.gateway.ScheduleList
	1,  // 25: wecom.gateway.WeComGateway.UpdateSchedule:output_type -> wecom.gateway.Schedule
	6,  // 26: wecom.gateway.WeComGateway.DeleteSchedule:output_type -> wecom.gateway.DeleteResponse
	9,  // 27: wecom.gateway.WeComGateway.ListMeetingRooms:output_type -> wecom.gateway.MeetingRoomList
	12, // 28: wecom.gateway.WeComGateway.GetRoomAvailability:output_type -> wecom.gateway.TimeSlotList
	14, // 29: wecom.gateway.WeComGateway.BookMeetingRoom:output_type -> wecom.gateway.BookingResult
	20, // 30: wecom.gateway.WeComGateway.SendText:output_type -> wecom.gateway.SendResult
	20, // 31: wecom.gateway.WeComGateway.SendMarkdown:output_type -> wecom.gateway.SendResult
	20, // 32: wecom.gateway.WeComGateway.SendImage:output_type -> wecom.gateway.SendResult
	20, // 33: wecom.gateway.WeComGateway.SendFile:output_type -> wecom.gateway.SendResult
	20, // 34: wecom.gateway.WeComGateway.SendCard:output_type -> wecom.gateway.SendResult
	22, // 35: wecom.gateway.WeComGatewayAdmin.CreateAPIKey:output_type -> wecom.gateway.APIKeyInfo
	24, // 36: wecom.gateway.WeComGatewayAdmin.ListAPIKeys:output_type -> wecom.gateway.APIKeyList
	6,  // 37: wecom.gateway.WeComGatewayAdmin.DeleteAPIKey:output_type -> wecom.gateway.DeleteResponse
	27, // 38: wecom.gateway.WeComGatewayAdmin.QueryAuditLogs:output_type -> wecom.gateway.AuditLogList
	30, // 39: wecom.gateway.WeComGatewayAdmin.GetDashboardStats:output_type -> wecom.gateway.DashboardStats
	23, // [23:40] is the sub-list for method output_type
	6,  // [6:23] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_wecom_gateway_proto_init() }
func file_api_proto_wecom_gateway_proto_init() {
	if File_api_proto_wecom_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_wecom_gateway_proto_rawDesc), len(file_api_proto_wecom_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_wecom_gateway_proto_goTypes,
		DependencyIndexes: file_api_proto_wecom_gateway_proto_depIdxs,
		MessageInfos:      file_api_proto_wecom_gateway_proto_msgTypes,
	}.Build()
	File_api_proto_wecom_gateway_proto = out.File
	file_api_proto_wecom_gateway_proto_goTypes = nil
	file_api_proto_wecom_gateway_proto_depIdxs = nil
}
