// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.29.5
// source: api/proto/wecom_gateway.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	WeComGateway_CreateSchedule_FullMethodName      = "/wecom.gateway.WeComGateway/CreateSchedule"
	WeComGateway_GetSchedules_FullMethodName        = "/wecom.gateway.WeComGateway/GetSchedules"
	WeComGateway_UpdateSchedule_FullMethodName      = "/wecom.gateway.WeComGateway/UpdateSchedule"
	WeComGateway_DeleteSchedule_FullMethodName      = "/wecom.gateway.WeComGateway/DeleteSchedule"
	WeComGateway_ListMeetingRooms_FullMethodName    = "/wecom.gateway.WeComGateway/ListMeetingRooms"
	WeComGateway_GetRoomAvailability_FullMethodName = "/wecom.gateway.WeComGateway/GetRoomAvailability"
	WeComGateway_BookMeetingRoom_FullMethodName     = "/wecom.gateway.WeComGateway/BookMeetingRoom"
	WeComGateway_SendText_FullMethodName            = "/wecom.gateway.WeComGateway/SendText"
	WeComGateway_SendMarkdown_FullMethodName        = "/wecom.gateway.WeComGateway/SendMarkdown"
	WeComGateway_SendImage_FullMethodName           = "/wecom.gateway.WeComGateway/SendImage"
	WeComGateway_SendFile_FullMethodName            = "/wecom.gateway.WeComGateway/SendFile"
	WeComGateway_SendCard_FullMethodName            = "/wecom.gateway.WeComGateway/SendCard"
)

// WeComGatewayClient is the client API for WeComGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WeCom Gateway Service
type WeComGatewayClient interface {
	// Schedule operations
	CreateSchedule(ctx context.Context, in *CreateScheduleRequest, opts ...grpc.CallOption) (*Schedule, error)
	GetSchedules(ctx context.Context, in *GetSchedulesRequest, opts ...grpc.CallOption) (*ScheduleList, error)
	UpdateSchedule(ctx context.Context, in *UpdateScheduleRequest, opts ...grpc.CallOption) (*Schedule, error)
	DeleteSchedule(ctx context.Context, in *DeleteScheduleRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Meeting room operations
	ListMeetingRooms(ctx context.Context, in *ListMeetingRoomsRequest, opts ...grpc.CallOption) (*MeetingRoomList, error)
	GetRoomAvailability(ctx context.Context, in *AvailabilityRequest, opts ...grpc.CallOption) (*TimeSlotList, error)
	BookMeetingRoom(ctx context.Context, in *BookMeetingRoomRequest, opts ...grpc.CallOption) (*BookingResult, error)
	// Message operations
	SendText(ctx context.Context, in *TextMessageRequest, opts ...grpc.CallOption) (*SendResult, error)
	SendMarkdown(ctx context.Context, in *MarkdownMessageRequest, opts ...grpc.CallOption) (*SendResult, error)
	SendImage(ctx context.Context, in *ImageMessageRequest, opts ...grpc.CallOption) (*SendResult, error)
	SendFile(ctx context.Context, in *FileMessageRequest, opts ...grpc.CallOption) (*SendResult, error)
	SendCard(ctx context.Context, in *CardMessageRequest, opts ...grpc.CallOption) (*SendResult, error)
}

type weComGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewWeComGatewayClient(cc grpc.ClientConnInterface) WeComGatewayClient {
	return &weComGatewayClient{cc}
}

func (c *weComGatewayClient) CreateSchedule(ctx context.Context, in *CreateScheduleRequest, opts ...grpc.CallOption) (*Schedule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Schedule)
	err := c.cc.Invoke(ctx, WeComGateway_CreateSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weComGatewayClient) GetSchedules(ctx context.Context, in *GetSchedulesRequest, opts ...grpc.CallOption) (*ScheduleList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleList)
	err := c.cc.Invoke(ctx, WeComGateway_GetSchedules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weComGatewayClient) UpdateSchedule(ctx context.Context, in *UpdateScheduleRequest, opts ...grpc.CallOption) (*Schedule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Schedule)
	err := c.cc.Invoke(ctx, WeComGateway_UpdateSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weComGatewayClient) DeleteSchedule(ctx context.Context, in *DeleteScheduleRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, WeComGateway_DeleteSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weComGatewayClient) ListMeetingRooms(ctx context.Context, in *ListMeetingRoomsRequest, opts ...grpc.CallOption) (*MeetingRoomList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeetingRoomList)
	err := c.cc.Invoke(ctx, WeComGateway_ListMeetingRooms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weComGatewayClient) GetRoomAvailability(ctx context.Context, in *AvailabilityRequest, opts ...grpc.CallOption) (*TimeSlotList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeSlotList)
	err := c.cc.Invoke(ctx, WeComGateway_GetRoomAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weComGatewayClient) BookMeetingRoom(ctx context.Context, in *BookMeetingRoomRequest, opts ...grpc.CallOption) (*BookingResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingResult)
	err := c.cc.Invoke(ctx, WeComGateway_BookMeetingRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weComGatewayClient) SendText(ctx context.Context, in *TextMessageRequest, opts ...grpc.CallOption) (*SendResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResult)
	err := c.cc.Invoke(ctx, WeComGateway_SendText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weComGatewayClient) SendMarkdown(ctx context.Context, in *MarkdownMessageRequest, opts ...grpc.CallOption) (*SendResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResult)
	err := c.cc.Invoke(ctx, WeComGateway_SendMarkdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weComGatewayClient) SendImage(ctx context.Context, in *ImageMessageRequest, opts ...grpc.CallOption) (*SendResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResult)
	err := c.cc.Invoke(ctx, WeComGateway_SendImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weComGatewayClient) SendFile(ctx context.Context, in *FileMessageRequest, opts ...grpc.CallOption) (*SendResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResult)
	err := c.cc.Invoke(ctx, WeComGateway_SendFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weComGatewayClient) SendCard(ctx context.Context, in *CardMessageRequest, opts ...grpc.CallOption) (*SendResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResult)
	err := c.cc.Invoke(ctx, WeComGateway_SendCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeComGatewayServer is the server API for WeComGateway service.
// All implementations must embed UnimplementedWeComGatewayServer
// for forward compatibility
//
// WeCom Gateway Service
type WeComGatewayServer interface {
	// Schedule operations
	CreateSchedule(context.Context, *CreateScheduleRequest) (*Schedule, error)
	GetSchedules(context.Context, *GetSchedulesRequest) (*ScheduleList, error)
	UpdateSchedule(context.Context, *UpdateScheduleRequest) (*Schedule, error)
	DeleteSchedule(context.Context, *DeleteScheduleRequest) (*DeleteResponse, error)
	// Meeting room operations
	ListMeetingRooms(context.Context, *ListMeetingRoomsRequest) (*MeetingRoomList, error)
	GetRoomAvailability(context.Context, *AvailabilityRequest) (*TimeSlotList, error)
	BookMeetingRoom(context.Context, *BookMeetingRoomRequest) (*BookingResult, error)
	// Message operations
	SendText(context.Context, *TextMessageRequest) (*SendResult, error)
	SendMarkdown(context.Context, *MarkdownMessageRequest) (*SendResult, error)
	SendImage(context.Context, *ImageMessageRequest) (*SendResult, error)
	SendFile(context.Context, *FileMessageRequest) (*SendResult, error)
	SendCard(context.Context, *CardMessageRequest) (*SendResult, error)
	mustEmbedUnimplementedWeComGatewayServer()
}

// UnimplementedWeComGatewayServer must be embedded to have forward compatible implementations.
type UnimplementedWeComGatewayServer struct {
}

func (UnimplementedWeComGatewayServer) CreateSchedule(context.Context, *CreateScheduleRequest) (*Schedule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSchedule not implemented")
}
func (UnimplementedWeComGatewayServer) GetSchedules(context.Context, *GetSchedulesRequest) (*ScheduleList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchedules not implemented")
}
func (UnimplementedWeComGatewayServer) UpdateSchedule(context.Context, *UpdateScheduleRequest) (*Schedule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSchedule not implemented")
}
func (UnimplementedWeComGatewayServer) DeleteSchedule(context.Context, *DeleteScheduleRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSchedule not implemented")
}
func (UnimplementedWeComGatewayServer) ListMeetingRooms(context.Context, *ListMeetingRoomsRequest) (*MeetingRoomList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMeetingRooms not implemented")
}
func (UnimplementedWeComGatewayServer) GetRoomAvailability(context.Context, *AvailabilityRequest) (*TimeSlotList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoomAvailability not implemented")
}
func (UnimplementedWeComGatewayServer) BookMeetingRoom(context.Context, *BookMeetingRoomRequest) (*BookingResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookMeetingRoom not implemented")
}
func (UnimplementedWeComGatewayServer) SendText(context.Context, *TextMessageRequest) (*SendResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendText not implemented")
}
func (UnimplementedWeComGatewayServer) SendMarkdown(context.Context, *MarkdownMessageRequest) (*SendResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMarkdown not implemented")
}
func (UnimplementedWeComGatewayServer) SendImage(context.Context, *ImageMessageRequest) (*SendResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendImage not implemented")
}
func (UnimplementedWeComGatewayServer) SendFile(context.Context, *FileMessageRequest) (*SendResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendFile not implemented")
}
func (UnimplementedWeComGatewayServer) SendCard(context.Context, *CardMessageRequest) (*SendResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCard not implemented")
}
func (UnimplementedWeComGatewayServer) mustEmbedUnimplementedWeComGatewayServer() {}

// UnsafeWeComGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeComGatewayServer will
// result in compilation errors.
type UnsafeWeComGatewayServer interface {
	mustEmbedUnimplementedWeComGatewayServer()
}

func RegisterWeComGatewayServer(s grpc.ServiceRegistrar, srv WeComGatewayServer) {
	s.RegisterService(&WeComGateway_ServiceDesc, srv)
}

func _WeComGateway_CreateSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeComGatewayServer).CreateSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeComGateway_CreateSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeComGatewayServer).CreateSchedule(ctx, req.(*CreateScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeComGateway_GetSchedules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchedulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeComGatewayServer).GetSchedules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeComGateway_GetSchedules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeComGatewayServer).GetSchedules(ctx, req.(*GetSchedulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeComGateway_UpdateSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeComGatewayServer).UpdateSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeComGateway_UpdateSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeComGatewayServer).UpdateSchedule(ctx, req.(*UpdateScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeComGateway_DeleteSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeComGatewayServer).DeleteSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeComGateway_DeleteSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeComGatewayServer).DeleteSchedule(ctx, req.(*DeleteScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeComGateway_ListMeetingRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMeetingRoomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeComGatewayServer).ListMeetingRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeComGateway_ListMeetingRooms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeComGatewayServer).ListMeetingRooms(ctx, req.(*ListMeetingRoomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeComGateway_GetRoomAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeComGatewayServer).GetRoomAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeComGateway_GetRoomAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeComGatewayServer).GetRoomAvailability(ctx, req.(*AvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeComGateway_BookMeetingRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookMeetingRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeComGatewayServer).BookMeetingRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeComGateway_BookMeetingRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeComGatewayServer).BookMeetingRoom(ctx, req.(*BookMeetingRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeComGateway_SendText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeComGatewayServer).SendText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeComGateway_SendText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeComGatewayServer).SendText(ctx, req.(*TextMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeComGateway_SendMarkdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkdownMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeComGatewayServer).SendMarkdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeComGateway_SendMarkdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeComGatewayServer).SendMarkdown(ctx, req.(*MarkdownMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeComGateway_SendImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeComGatewayServer).SendImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeComGateway_SendImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeComGatewayServer).SendImage(ctx, req.(*ImageMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeComGateway_SendFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeComGatewayServer).SendFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeComGateway_SendFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeComGatewayServer).SendFile(ctx, req.(*FileMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeComGateway_SendCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeComGatewayServer).SendCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeComGateway_SendCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeComGatewayServer).SendCard(ctx, req.(*CardMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WeComGateway_ServiceDesc is the grpc.ServiceDesc for WeComGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeComGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wecom.gateway.WeComGateway",
	HandlerType: (*WeComGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSchedule",
			Handler:    _WeComGateway_CreateSchedule_Handler,
		},
		{
			MethodName: "GetSchedules",
			Handler:    _WeComGateway_GetSchedules_Handler,
		},
		{
			MethodName: "UpdateSchedule",
			Handler:    _WeComGateway_UpdateSchedule_Handler,
		},
		{
			MethodName: "DeleteSchedule",
			Handler:    _WeComGateway_DeleteSchedule_Handler,
		},
		{
			MethodName: "ListMeetingRooms",
			Handler:    _WeComGateway_ListMeetingRooms_Handler,
		},
		{
			MethodName: "GetRoomAvailability",
			Handler:    _WeComGateway_GetRoomAvailability_Handler,
		},
		{
			MethodName: "BookMeetingRoom",
			Handler:    _WeComGateway_BookMeetingRoom_Handler,
		},
		{
			MethodName: "SendText",
			Handler:    _WeComGateway_SendText_Handler,
		},
		{
			MethodName: "SendMarkdown",
			Handler:    _WeComGateway_SendMarkdown_Handler,
		},
		{
			MethodName: "SendImage",
			Handler:    _WeComGateway_SendImage_Handler,
		},
		{
			MethodName: "SendFile",
			Handler:    _WeComGateway_SendFile_Handler,
		},
		{
			MethodName: "SendCard",
			Handler:    _WeComGateway_SendCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/wecom_gateway.proto",
}

const (
	WeComGatewayAdmin_CreateAPIKey_FullMethodName      = "/wecom.gateway.WeComGatewayAdmin/CreateAPIKey"
	WeComGatewayAdmin_ListAPIKeys_FullMethodName       = "/wecom.gateway.WeComGatewayAdmin/ListAPIKeys"
	WeComGatewayAdmin_DeleteAPIKey_FullMethodName      = "/wecom.gateway.WeComGatewayAdmin/DeleteAPIKey"
	WeComGatewayAdmin_QueryAuditLogs_FullMethodName    = "/wecom.gateway.WeComGatewayAdmin/QueryAuditLogs"
	WeComGatewayAdmin_GetDashboardStats_FullMethodName = "/wecom.gateway.WeComGatewayAdmin/GetDashboardStats"
)

// WeComGatewayAdminClient is the client API for WeComGatewayAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Admin Service
type WeComGatewayAdminClient interface {
	// API Key management
	CreateAPIKey(ctx context.Context, in *CreateAPIKeyRequest, opts ...grpc.CallOption) (*APIKeyInfo, error)
	ListAPIKeys(ctx context.Context, in *ListAPIKeysRequest, opts ...grpc.CallOption) (*APIKeyList, error)
	DeleteAPIKey(ctx context.Context, in *DeleteAPIKeyRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Audit logs
	QueryAuditLogs(ctx context.Context, in *QueryAuditLogsRequest, opts ...grpc.CallOption) (*AuditLogList, error)
	// Dashboard
	GetDashboardStats(ctx context.Context, in *DashboardStatsRequest, opts ...grpc.CallOption) (*DashboardStats, error)
}

type weComGatewayAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewWeComGatewayAdminClient(cc grpc.ClientConnInterface) WeComGatewayAdminClient {
	return &weComGatewayAdminClient{cc}
}

func (c *weComGatewayAdminClient) CreateAPIKey(ctx context.Context, in *CreateAPIKeyRequest, opts ...grpc.CallOption) (*APIKeyInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(APIKeyInfo)
	err := c.cc.Invoke(ctx, WeComGatewayAdmin_CreateAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weComGatewayAdminClient) ListAPIKeys(ctx context.Context, in *ListAPIKeysRequest, opts ...grpc.CallOption) (*APIKeyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(APIKeyList)
	err := c.cc.Invoke(ctx, WeComGatewayAdmin_ListAPIKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weComGatewayAdminClient) DeleteAPIKey(ctx context.Context, in *DeleteAPIKeyRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, WeComGatewayAdmin_DeleteAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weComGatewayAdminClient) QueryAuditLogs(ctx context.Context, in *QueryAuditLogsRequest, opts ...grpc.CallOption) (*AuditLogList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditLogList)
	err := c.cc.Invoke(ctx, WeComGatewayAdmin_QueryAuditLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weComGatewayAdminClient) GetDashboardStats(ctx context.Context, in *DashboardStatsRequest, opts ...grpc.CallOption) (*DashboardStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DashboardStats)
	err := c.cc.Invoke(ctx, WeComGatewayAdmin_GetDashboardStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeComGatewayAdminServer is the server API for WeComGatewayAdmin service.
// All implementations must embed UnimplementedWeComGatewayAdminServer
// for forward compatibility
//
// Admin Service
type WeComGatewayAdminServer interface {
	// API Key management
	CreateAPIKey(context.Context, *CreateAPIKeyRequest) (*APIKeyInfo, error)
	ListAPIKeys(context.Context, *ListAPIKeysRequest) (*APIKeyList, error)
	DeleteAPIKey(context.Context, *DeleteAPIKeyRequest) (*DeleteResponse, error)
	// Audit logs
	QueryAuditLogs(context.Context, *QueryAuditLogsRequest) (*AuditLogList, error)
	// Dashboard
	GetDashboardStats(context.Context, *DashboardStatsRequest) (*DashboardStats, error)
	mustEmbedUnimplementedWeComGatewayAdminServer()
}

// UnimplementedWeComGatewayAdminServer must be embedded to have forward compatible implementations.
type UnimplementedWeComGatewayAdminServer struct {
}

func (UnimplementedWeComGatewayAdminServer) CreateAPIKey(context.Context, *CreateAPIKeyRequest) (*APIKeyInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAPIKey not implemented")
}
func (UnimplementedWeComGatewayAdminServer) ListAPIKeys(context.Context, *ListAPIKeysRequest) (*APIKeyList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAPIKeys not implemented")
}
func (UnimplementedWeComGatewayAdminServer) DeleteAPIKey(context.Context, *DeleteAPIKeyRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAPIKey not implemented")
}
func (UnimplementedWeComGatewayAdminServer) QueryAuditLogs(context.Context, *QueryAuditLogsRequest) (*AuditLogList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryAuditLogs not implemented")
}
func (UnimplementedWeComGatewayAdminServer) GetDashboardStats(context.Context, *DashboardStatsRequest) (*DashboardStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardStats not implemented")
}
func (UnimplementedWeComGatewayAdminServer) mustEmbedUnimplementedWeComGatewayAdminServer() {}

// UnsafeWeComGatewayAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeComGatewayAdminServer will
// result in compilation errors.
type UnsafeWeComGatewayAdminServer interface {
	mustEmbedUnimplementedWeComGatewayAdminServer()
}

func RegisterWeComGatewayAdminServer(s grpc.ServiceRegistrar, srv WeComGatewayAdminServer) {
	s.RegisterService(&WeComGatewayAdmin_ServiceDesc, srv)
}

func _WeComGatewayAdmin_CreateAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeComGatewayAdminServer).CreateAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeComGatewayAdmin_CreateAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeComGatewayAdminServer).CreateAPIKey(ctx, req.(*CreateAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeComGatewayAdmin_ListAPIKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAPIKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeComGatewayAdminServer).ListAPIKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeComGatewayAdmin_ListAPIKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeComGatewayAdminServer).ListAPIKeys(ctx, req.(*ListAPIKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeComGatewayAdmin_DeleteAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeComGatewayAdminServer).DeleteAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeComGatewayAdmin_DeleteAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeComGatewayAdminServer).DeleteAPIKey(ctx, req.(*DeleteAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeComGatewayAdmin_QueryAuditLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAuditLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeComGatewayAdminServer).QueryAuditLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeComGatewayAdmin_QueryAuditLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeComGatewayAdminServer).QueryAuditLogs(ctx, req.(*QueryAuditLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeComGatewayAdmin_GetDashboardStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DashboardStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeComGatewayAdminServer).GetDashboardStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeComGatewayAdmin_GetDashboardStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeComGatewayAdminServer).GetDashboardStats(ctx, req.(*DashboardStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WeComGatewayAdmin_ServiceDesc is the grpc.ServiceDesc for WeComGatewayAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeComGatewayAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wecom.gateway.WeComGatewayAdmin",
	HandlerType: (*WeComGatewayAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAPIKey",
			Handler:    _WeComGatewayAdmin_CreateAPIKey_Handler,
		},
		{
			MethodName: "ListAPIKeys",
			Handler:    _WeComGatewayAdmin_ListAPIKeys_Handler,
		},
		{
			MethodName: "DeleteAPIKey",
			Handler:    _WeComGatewayAdmin_DeleteAPIKey_Handler,
		},
		{
			MethodName: "QueryAuditLogs",
			Handler:    _WeComGatewayAdmin_QueryAuditLogs_Handler,
		},
		{
			MethodName: "GetDashboardStats",
			Handler:    _WeComGatewayAdmin_GetDashboardStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/wecom_gateway.proto",
}
